# Default values for SampleService service.
replicaCount: 3
revisionHistoryLimit: 0

image:
  tag: ""

service:
  port: 9000

ingress:
  host: ""
  annotations: {}

resources:
  limits:
    memory: "512M"
  requests:
    memory: "512M"

java:
  debugEnabled: true
  initMemRation: 40
  maxMemRation: 70
  options: >-
     -Dconfig.resource=application-docker.conf
     -Dlogger.file=/opt/lib/logback-prod.xml
     -XshowSettings:vm
     -XX:+UnlockExperimentalVMOptions
     -XX:+UseCGroupMemoryLimitForHeap
     -XX:+PrintGCDetails
     -XX:+PrintGCDateStamps
     -Xloggc:/var/log/gc.log
     -XX:+UseGCLogFileRotation
     -XX:NumberOfGCLogFiles=10
     -XX:GCLogFileSize=32M
     -Dhttp.proxyHost=todo_proxy_server
     -Dhttp.proxyPort=80
     -Dhttps.proxyHost=todo_proxy_server
     -Dhttps.proxyPort=80

nonProxyHosts: "localhost|*.todo_inner_net.ru"

config: ""

logstash: ""
