language: java

services:
- docker
env:
- SOME_ENV=eee

matrix:
  fast_finish: true

before_cache:
- rm -fr  $HOME/.m2/repository
cache:
  directories:
  - $HOME/.m2/repository/
  - $HOME/.m2/wrapper/

script:
- ./mvn clean verify

after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- echo $GPG_SECRET_KEYS | base64 --decode > $HOME/.gnupg/shadewallcorp.gpg

deploy:
  provider: script
  script: "cp /travis/.travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true # to upload artifacts created during the build
  on:
    tags: true

notifications:
  email:
    recipients:
    - gugle.day.zaregitsya@gmail.com
    on_success: change
    on_failure: always

# https://blog.travis-ci.com/2017-03-30-deploy-maven-travis-ci-packagecloud/