image: cloudbees/java-with-docker-client:8-jdk-18.06.1-ce

cache:
  key: "$CI_PROJECT_ID"
  untracked: false
  paths:
  - ".m2"

services:
- name: docker:18-dind
  command: ["--insecure-registry=todo_nexus_server:8888"]

variables:
  MAVEN_USER_HOME: .m2
  MAVEN_OPTS: >-
    -Duser.home=$CI_PROJECT_DIR
    -Dhttp.proxyHost=todo_proxy_server
    -Dhttp.proxyPort=80
    -Dhttps.proxyHost=todo_proxy_server
    -Dhttps.proxyPort=80
    -Dhttp.nonProxyHosts=todo_nexus_server
  DOCKER_HOST: tcp://docker:2375
  HTTPS_PROXY: http://todo_proxy_server:80
  HTTP_PROXY: http://todo_proxy_server:80
  NO_PROXY: todo_test_server-kube-master-01,todo_nexus_server,docker
  K8S_SERVER: https://todo_test_server-kube-master-01:6443

before_script:
- mkdir -p ${MAVEN_USER_HOME}
- cp $CI_PROJECT_DIR/m2_settings.xml ${MAVEN_USER_HOME}/settings.xml
- sed -i'' -r 's|NEXUS_USER|'$NEXUS_USER'|g' ${MAVEN_USER_HOME}/settings.xml
- sed -i'' -r 's|NEXUS_PASSWORD|'$NEXUS_PASSWORD'|g' ${MAVEN_USER_HOME}/settings.xml

stages:
- build_common
- build
- install
- update
- delete
- del_ES_index
- new_ES_index

Build:
  stage: build_common
  script:
  - "./mvnw clean verify"
  except:
  - tags

Build snapshot:
  stage: build_common
  script:
  - "./mvnw clean deploy --projects topic,api,impl --also-make"
  when: manual
  except:
  - tags

Build chart snapshot:
  stage: build_common
  image: todo_nexus_server:8888/todo-repo-name/k8s-helm:v2.13.1
  before_script:
  - helm repo add nexus-snapshots http://todo_nexus_server:8081/repository/helm-snapshots/
  script:
  - helm nexus-push nexus-snapshots helm/orders --username "$NEXUS_USER" --password "$NEXUS_PASSWORD"
  when: manual
  except:
  - tags

Build release:
  stage: build_common
  script:
  - "./mvnw clean deploy"
  only:
  - tags

Build chart release:
  stage: build_common
  image: todo_nexus_server:8888/todo-repo-name/k8s-helm:v2.13.1
  before_script:
  - helm repo add nexus-releases http://todo_nexus_server:8081/repository/helm-releases/
  script:
  - helm nexus-push nexus-releases helm/orders --username "$NEXUS_USER" --password "$NEXUS_PASSWORD"
  only:
  - tags

.build_template: &build_def
  stage: build
  script:
    - "./mvnw clean deploy"
  when: manual

.install_template: &install_def
  stage: install
  image: todo_nexus_server:8888/todo-repo-name/k8s-helm:v2.13.1
  before_script:
    - sed -i'' -r 's|K8S_TOKEN|'$K8S_TOKEN'|g' ${CI_PROJECT_DIR}/kube_config
    - helm repo add nexus-snapshots http://todo_nexus_server:8081/repository/helm-snapshots/
  script:
    - "helm install nexus-snapshots/orders
      --kubeconfig ${CI_PROJECT_DIR}/kube_config
      --name orders-${CI_ENVIRONMENT_NAME}
      --namespace ${CI_ENVIRONMENT_NAME}
      --set-file config=${CI_PROJECT_DIR}/impl/src/main/resources/application-k8s-test.conf
      --set ingress.host=todo_test_server-kube-${CI_ENVIRONMENT_NAME}
      --set kafka.brokers=kafka-${CI_ENVIRONMENT_NAME}:9092
      --set image.tag=${DOCKER_IMAGE_VERSION}
      --set java.debugEnabled=true
      --set dbUrl=${DB_URL}
      --set elasticSearchHost=reactive-sandbox-${CI_ENVIRONMENT_NAME}-reactive-sandbox-elasticsearch.${CI_ENVIRONMENT_NAME}
      --set elasticSearchPort=9200
      --set cassandraUrl=_cql._tcp.reactive-sandbox-${CI_ENVIRONMENT_NAME}-reactive-sandbox-cassandra.${CI_ENVIRONMENT_NAME}
      --set nonProxyHosts=${NON_PROXY_HOSTS}"
  when: manual

.update_template: &update_def
  stage: update
  image: todo_nexus_server:8888/todo-repo-name/k8s-helm:v2.13.1
  before_script:
  - sed -i'' -r 's|K8S_TOKEN|'$K8S_TOKEN'|g' ${CI_PROJECT_DIR}/kube_config
  - helm repo add nexus-snapshots http://todo_nexus_server:8081/repository/helm-snapshots/
  script:
  - "helm upgrade orders-${CI_ENVIRONMENT_NAME} nexus-snapshots/orders
      --kubeconfig ${CI_PROJECT_DIR}/kube_config
      --namespace ${CI_ENVIRONMENT_NAME}
      --set-file config=${CI_PROJECT_DIR}/impl/src/main/resources/application-k8s-test.conf
      --set ingress.host=todo_test_server-kube-${CI_ENVIRONMENT_NAME}
      --set kafka.brokers=kafka-${CI_ENVIRONMENT_NAME}:9092
      --set image.tag=${DOCKER_IMAGE_VERSION}
      --set java.debugEnabled=true
      --set dbUrl=${DB_URL}
      --set elasticSearchHost=reactive-sandbox-${CI_ENVIRONMENT_NAME}-reactive-sandbox-elasticsearch.${CI_ENVIRONMENT_NAME}
      --set elasticSearchPort=9200
      --set cassandraUrl=_cql._tcp.reactive-sandbox-${CI_ENVIRONMENT_NAME}-reactive-sandbox-cassandra.${CI_ENVIRONMENT_NAME}
      --set nonProxyHosts=${NON_PROXY_HOSTS}"
  when: manual

.delete_template: &delete_def
  stage: delete
  image: todo_nexus_server:8888/todo-repo-name/k8s-helm:v2.13.1
  before_script:
  - sed -i'' -r 's|K8S_TOKEN|'$K8S_TOKEN'|g' ${CI_PROJECT_DIR}/kube_config
  script:
  - helm delete --purge --kubeconfig ${CI_PROJECT_DIR}/kube_config orders-${CI_ENVIRONMENT_NAME}
  when: manual

.del_ES_index_template: &del_ES_index_def
  stage: del_ES_index
  script:
  - ./gitlab-ci/k8s_test_ES_delete_index.sh
  when: manual

.new_ES_index_template: &new_ES_index_def
  stage: new_ES_index
  script:
  - ./gitlab-ci/k8s_test_ES_create_index.sh
  when: manual
